### ISSUE TITLE
(feature) transform a patient into an Employee

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#2290] opened 2017-11-17 10:24 UTC
This issue proposes to transform a patient into an employee, so as not to allow the use of the employee module which, by default, creates a new patient each time an employee is registered.

**Comment by jniles** [comment] 2017-12-06 08:09
@lomamech, what is the state of this issue?

**Comment by jniles** [comment] 2018-02-23 09:50
Duplicate of #1632

**Closed as completed** 2018-05-24 10:36 UTC
