### ISSUE TITLE
Implement a debtor group age

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#812] opened 2016-10-18 12:32 UTC
## Description

This issue concerns implementing a report for showing the debt of client by period, periods are : 
- previous fiscal year
- more than six month
- Between three and six month
- less than three month

The grouping period can be discussed, with there is a better suggestion
## Technical Info

The data will be fetched from the general ledger, the report belongs to a financial group, this issue references #636

**Comment by jniles** [comment] 2016-11-03 13:18
This is kind of a duplicate of #635.

**Comment by jniles** [comment] 2016-11-08 12:26
This was closed in a merge to master.

**Closed as completed by jniles** 2016-11-08 12:26 UTC
