### ISSUE TITLE
(spec) Vanga release candidate requirements

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1146] opened 2017-02-08 09:24 UTC
Specification sheet for completing installation release candidate. Requirements defined by @jniles, @sfount.
 
1. **Cashflow Report**
  * Ensure report meets latest development standards (All Maths calculated in MySQL https://github.com/Vanga-Hospital/bhima-2.X/issues/204) - https://github.com/IMA-WorldHealth/bhima-2.X/issues/1145
  * Remaining bug reports and issues addressed 
~~https://github.com/IMA-WorldHealth/bhima-2.X/issues/1003~~ (Could not reproduce)
~~https://github.com/IMA-WorldHealth/bhima-2.X/issues/919~~ (Could not reproduce)

2. **Complex Voucher usability**
* ~~Reference grid inline filtering - https://github.com/IMA-WorldHealth/bhima-2.X/issues/1129~~
* ~~Reference grid default filtering - https://github.com/IMA-WorldHealth/bhima-2.X/issues/1138~~
* ~~Reference grid loading indicator - https://github.com/IMA-WorldHealth/bhima-2.X/issues/1127~~
* Debtor select UI-select performance issues **[Requires Issue]** 
*(Looking up debtor by name is a ui-select that will never work on low-end machines)*
* ~~Voucher Receipt should clearly display transaction type~~
* ~~Misc. UI fixes - https://github.com/IMA-WorldHealth/bhima-2.X/issues/1139~~
* Improvements to debt transfer - https://github.com/Vanga-Hospital/bhima-2.X/issues/208

3. **Posting Journal usability**
* Editing transactions - https://github.com/IMA-WorldHealth/bhima-2.X/issues/1030
*(Deleting transactions + corner cases with receipts/ outdated transactions)*
* ~~Remove aggregation labels - https://github.com/IMA-WorldHealth/bhima-2.X/issues/1110~~
* Trial balance performance issues **[Requires Issue]**
* ~~Trial balance `entity_type_id` warning should be removed; the user cannot do anything about this - https://github.com/IMA-WorldHealth/bhima-2.X/issues/584~~
* Refactor General Ledger **[Requires Issue]**

4. **Patient financial activity report** 
* ~~Voucher + Cash Payment identifiers - https://github.com/Vanga-Hospital/bhima-2.X/issues/254~~
* ~~Patient reference - https://github.com/IMA-WorldHealth/bhima-2.X/issues/1131~~

5. **Transfer cash from caisse** **[Requires Spec]** 
*(Vanga is currently not capturing all the data, this would allow them to have all transactions from the Caisse to the central Coffres to be correct.  They could write off all the rest.)*

6. **Reports** 
*(All reports fully tested with latest installation data set)*
* Refactor Income vs. Expense (Variance) report **[Requires Issue]** 
* Refactor Balance Sheet **[Requires Issue]**
* Refactor account detail report **[Requires Issue]** 
* ~~Open Debtors Report - https://github.com/Vanga-Hospital/bhima-2.X/issues/188~~

**Comment by mbayopanda** [comment] 2017-02-15 11:55
@jniles, @sfount in the point 1, i can't reproduce errors relatives to #1003 and #919. They are not yet fixed ?

**Comment by jniles** [comment] 2017-02-15 12:48
@mbayopanda, apparently they seem to have been fixed.  They are old issues, you can close them as "Cannot reproduce."

**Comment by jniles** [comment] 2017-05-03 06:22
Closing this as outdated.  We can make a new spec sheet after this Vanga trip.

**Closed as completed** 2017-05-23 15:27 UTC
