### ISSUE TITLE
Bhima crashes during depots loading in the user permission

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5699] opened 2021-05-26 00:06 UTC
![image](https://user-images.githubusercontent.com/5445251/119583410-7b991d00-bdbe-11eb-92b8-2fd33fe313c5.png)

Administration -> Users -> Depots Permission

**Comment by jniles** [comment] 2021-05-26 04:59
That looks like the pepkits database.  Is this bug on master or on the pepkits version of BHIMA?

Also, how many depots do we have in the pepkits database?

**Comment by mbayopanda** [comment] 2021-05-26 14:53
> That looks like the pepkits database. Is this bug on master or on the pepkits version of BHIMA?
> 
> Also, how many depots do we have in the pepkits database?

![image](https://user-images.githubusercontent.com/5445251/119682026-7679b380-be3a-11eb-9359-2cb426b9656e.png)

10815 depots

**Comment by jniles** [comment] 2021-05-26 18:18
Oh my goodness.  Well, I wonder what the solution to this is.  We can try to improve the performance of the component, but I'm not sure showing 10,000+ checkboxes is a good idea.

**Comment by jniles** [comment] 2024-11-14 20:22
I'm going to close this as a "won't fix".  I think the problem is likely that we shouldn't try to load in 10K+ depots.  If we wanted to, we should change this interface to be something else.

**Closed as completed by jniles** 2024-11-14 20:22 UTC
Labels: Bug, Stock
