### ISSUE TITLE
fix(journal voucher) : prise en charge by user ID doesn't work

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1958] opened 2017-08-09 13:56 UTC
The import tool for the prise en charge doesn't work properly when we select the patient using his ID. Instead of having two lines for the transaction, we just have one line

**Comment by jniles** [comment] 2017-08-09 14:25
Duplicate of https://github.com/IMA-WorldHealth/bhima-2.X/issues/1915

**Closed as completed by jniles** 2017-08-09 14:25 UTC
Labels: Bug
